server:
  port: 8080

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace

spring:
  sql:
    init:
      mode: always

  kafka:
    bootstrap-servers: localhost:9092  # adresse du broker Kafka
    consumer:
      group-id: startup-insight-engine # identifiant du groupe de consumers
      auto-offset-reset: earliest       # relit depuis le début si pas d'offset
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  datasource:
    url: jdbc:postgresql://localhost:5433/startup_insight
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true  # waiting for scheam ready before seeding database

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

  cache:
    type: redis
    redis:
      time-to-live: 600000

